name: Auto generate pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site-cv # Assure-toi que ce dossier contient les fichiers à publier

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Get the output URL
        run: echo "The deployment URL is ${{ steps.deployment.outputs.page_url }}"